Add checks for API executable and required directories in build workflow

diff --git a/.github/workflows/build_api.yml b/.github/workflows/build_api.yml
--- a/.github/workflows/build_api.yml
+++ b/.github/workflows/build_api.yml
@@ -92,3 +92,18 @@ jobs:
 
           echo "rpi_ai/"
           ls -l
+
+          if [ ! -f "rpi-ai" ]; then
+            echo "API executabe not found"
+            exit 1
+          fi
+
+          if [ ! -d "config" ]; then
+            echo "Config directory not found"
+            exit 1
+          fi
+
+          if [ ! -d "logs" ]; then
+            echo "Logs directory not found"
+            exit 1
+          fi
