Revert "Refactor installation process to install directly from GitHub repository instead of wheel file"
This reverts commit 8e856f90826a6fa918c347ea6466ed89c1eccbd8.

diff --git a/.github/workflows/build_api.yml b/.github/workflows/build_api.yml
--- a/.github/workflows/build_api.yml
+++ b/.github/workflows/build_api.yml
@@ -7,23 +7,45 @@ on:
   workflow_dispatch:
 
 jobs:
-  create_installer:
+  build_wheel:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - uses: ./.github/actions/setup-python-core
+      - name: Create wheel
+        run: |
+          uv build
+      - name: Upload wheel
+        uses: actions/upload-artifact@v4
+        with:
+          name: rpi_ai_wheel
+          path: dist/rpi_ai-*-py3-none-any.whl
+  create_installer:
+    runs-on: ubuntu-latest
+    needs: [build_wheel]
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ./.github/actions/setup-python-core
+      - name: Download backend artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: rpi_ai_wheel
       - name: Prepare release directory
         run: |
           PACKAGE_NAME="rpi_ai"
-          PACKAGE_VERSION=$(uv run python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])")
+          WHEEL_FILE=$(find . -name "${PACKAGE_NAME}-*-py3-none-any.whl")
+          PACKAGE_VERSION=$(echo "$WHEEL_FILE" | sed -n "s/.*${PACKAGE_NAME}-\(.*\)-py3-none-any\.whl/\1/p")
 
+          mv "$WHEEL_FILE" release/
+          chmod +x release/install_rpi_ai.sh
           mv release ${PACKAGE_NAME}_${PACKAGE_VERSION}
 
           tree ${PACKAGE_NAME}_${PACKAGE_VERSION} --dirsfirst -F
       - name: Create release tarball
         run: |
           PACKAGE_NAME="rpi_ai"
-          PACKAGE_VERSION=$(uv run python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])")
+          WHEEL_FILE=$(find . -name "${PACKAGE_NAME}-*-py3-none-any.whl")
+          PACKAGE_VERSION=$(echo "$WHEEL_FILE" | sed -n "s/.*${PACKAGE_NAME}-\(.*\)-py3-none-any\.whl/\1/p")
           tar -czf ${PACKAGE_NAME}_${PACKAGE_VERSION}.tar.gz ${PACKAGE_NAME}_${PACKAGE_VERSION}
       - name: Upload release tarball
         uses: actions/upload-artifact@v4
@@ -54,7 +76,16 @@ jobs:
           echo "$DIR_NAME/"
           tree --dirsfirst -F
 
+          WHEEL_FILE=$(find . -name "${PACKAGE_NAME}-*-py3-none-any.whl")
+          files=("${WHEEL_FILE}")
           scripts=("install_rpi_ai.sh")
+
+          for file in "${files[@]}"; do
+            if [ ! -f "$file" ]; then
+              echo "File $file not found"
+              exit 1
+            fi
+          done
 
           for script in "${scripts[@]}"; do
             if [ ! -f "$script" ]; then
@@ -88,6 +119,11 @@ jobs:
 
           if [ -f "install_rpi_ai.sh" ]; then
             echo "Installer script not removed"
+            exit 1
+          fi
+
+          if [ -f "$(find . -name 'rpi_ai-*-py3-none-any.whl')" ]; then
+            echo "Wheel file not removed"
             exit 1
           fi
 
