Refactor build_api.yml: enhance verification steps for pre and post-installation directories

diff --git a/.github/workflows/build_api.yml b/.github/workflows/build_api.yml
--- a/.github/workflows/build_api.yml
+++ b/.github/workflows/build_api.yml
@@ -66,6 +66,34 @@ jobs:
         run: |
           TAR_FILE=$(find . -name 'rpi_ai_*.tar.gz')
           tar -xzf $TAR_FILE
+      - name: Verify pre-installation directory contents
+        run: |
+          TAR_FILE=$(find . -name 'rpi_ai_*.tar.gz')
+          DIR_NAME=$(basename "$TAR_FILE" .tar.gz)
+          PACKAGE_NAME="rpi_ai"
+          WHEEL_FILE=$(find . -name "${PACKAGE_NAME}-*-py3-none-any.whl")
+          cd "$DIR_NAME"
+
+          files=("${WHEEL_FILE}")
+          scripts=("install_rpi_ai.sh")
+
+          for file in "${files[@]}"; do
+            if [ ! -f "$file" ]; then
+              echo "File $file not found"
+              exit 1
+            fi
+          done
+
+          for script in "${scripts[@]}"; do
+            if [ ! -f "$script" ]; then
+              echo "Script $script not found"
+              exit 1
+            fi
+            if [ ! -x "$script" ]; then
+              echo "Script $script is not executable"
+              exit 1
+            fi
+          done
       - name: Run installer script
         env:
           GEMINI_API_KEY: dummy
@@ -77,6 +105,12 @@ jobs:
           export GEMINI_API_KEY="test"
           ./install_rpi_ai.sh
 
+      - name: Verify post-installation directory contents
+        run: |
+          TAR_FILE=$(find . -name 'rpi_ai_*.tar.gz')
+          DIR_NAME=$(basename "$TAR_FILE" .tar.gz)
+
+          cd "$DIR_NAME"
           echo "$DIR_NAME/"
           tree --dirsfirst -F
 
@@ -90,47 +124,31 @@ jobs:
             exit 1
           fi
 
-          if [ ! -d ".venv" ]; then
-            echo "Virtual environment not found"
-            exit 1
-          fi
+          folders=(".venv" "logs")
+          files=("rpi-ai" "${HOME}/.config/rpi_ai/ai_config.json" "service/rpi-ai.service" "uninstall_rpi_ai.sh" "README.txt")
+          scripts=("service/start_service.sh" "service/stop_service.sh")
 
-          if [ ! -f "rpi-ai" ]; then
-            echo "API executable not found"
-            exit 1
-          fi
+          for folder in "${folders[@]}"; do
+            if [ ! -d "$folder" ]; then
+              echo "Folder $folder not found"
+              exit 1
+            fi
+          done
 
-          if [ ! -f "${HOME}/.config/rpi_ai/ai_config.json" ]; then
-            echo "Config directory not found"
-            exit 1
-          fi
+          for file in "${files[@]}"; do
+            if [ ! -f "$file" ]; then
+              echo "File $file not found"
+              exit 1
+            fi
+          done
 
-          if [ ! -d "logs" ]; then
-            echo "Logs directory not found"
-            exit 1
-          fi
-
-          if [ ! -f "service/rpi-ai.service" ]; then
-            echo "Service file not found"
-            exit 1
-          fi
-
-          if [ ! -f "service/start_service.sh" ]; then
-            echo "Service creation file not found"
-            exit 1
-          fi
-
-          if [ ! -f "service/stop_service.sh" ]; then
-            echo "Service stopping file not found"
-            exit 1
-          fi
-
-          if [ ! -f "uninstall_rpi_ai.sh" ]; then
-            echo "Uninstallation file not found"
-            exit 1
-          fi
-
-          if [ ! -f "README.txt" ]; then
-            echo "README file not found"
-            exit 1
-          fi
+          for script in "${scripts[@]}"; do
+            if [ ! -f "$script" ]; then
+              echo "Script $script not found"
+              exit 1
+            fi
+            if [ ! -x "$script" ]; then
+              echo "Script $script is not executable"
+              exit 1
+            fi
+          done
